import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const redirect = () => {
    window.location.href = 'https://rnbwapp.com';
  };

  const redirectWithWork = async () => {
    // const response = await fetch(
    //   'https://registry.walletconnect.org/data/wallets.json',
    // );
    await new Promise((resolve) => {
      setTimeout(() => {
        resolve(undefined);
      }, 1000);
    });

    window.location.assign('https://rnbwapp.com');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <button onClick={redirect}>bare redirect</button>
        <button onClick={redirectWithWork}>redirect with work</button>
      </main>
    </div>
  );
};

export default Home;
