import WalletConnect from '@walletconnect/client';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [address, setAddress] = useState('');

  const client = new WalletConnect({
    bridge: 'https://bridge.walletconnect.org',
  });

  const handleConnect = async () => {
    await client.createSession();

    const deepLink = `https://rnbwapp.com/wc?uri=${encodeURIComponent(
      client.uri ?? '',
    )}`;
    window.location.href = deepLink;

    return new Promise((resolve, reject) => {
      // ...then once the QR is scanned, this callback will run
      client.on('connect', (error: Error | null, payload: any) => {
        if (error) {
          reject(error);
        }

        const [accountPublicAddress] = payload.params[0].accounts;
        resolve(accountPublicAddress);
        setAddress(accountPublicAddress);
      });

      client.on('disconnect', (error: Error | null, payload: any) => {
        reject(error || payload.params[0].message);
      });
    });
  };

  const handleSign = async () => {
    const response = await fetch(
      'https://registry.walletconnect.org/data/wallets.json',
    );
    const data = await response.json();
    console.log({ data });

    const deepLink = `https://rnbwapp.com/wc?uri=${encodeURIComponent(
      client.uri ?? '',
    )}`;
    window.location.assign(deepLink);

    try {
      await client.signPersonalMessage(['example', address]);
    } catch (e) {
      console.log(e);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>address: {address}</div>

      <main className={styles.main}>
        <button onClick={handleConnect}>Connect</button>
        <button onClick={handleSign}>Sign</button>
      </main>
    </div>
  );
};

export default Home;
