import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const redirect = () => {
    window.location.href = 'https://rnbwapp.com';
  };

  const redirectAfterFetch = async () => {
    await fetch('https://registry.walletconnect.org/data/wallets.json');

    window.location.assign('https://rnbwapp.com');
  };

  const redirectAfterTimeout = async (timeout: number) => {
    await new Promise((resolve) => {
      setTimeout(() => {
        resolve(undefined);
      }, timeout);
    });

    window.location.assign('https://rnbwapp.com');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <button onClick={redirect}>redirect</button>
        <button onClick={redirectAfterFetch}>redirect (fetch)</button>
        <button onClick={() => redirectAfterTimeout(990)}>
          redirect (timeout 990ms)
        </button>
        <button onClick={() => redirectAfterTimeout(1000)}>
          redirect (timeout 1000ms)
        </button>
      </main>
    </div>
  );
};

export default Home;
